// ======================================================================
// Author : $Author$
// Version: $Revision: 307 $
// Date   : $Date: 2012-04-22 18:51:48 +0000 (Sun, 22 Apr 2012) $
// Url    : $URL$
// ======================================================================

// ======================================================================
//  _/|            __
// // o\         /    )           ,        /    /
// || ._)    ----\---------__----------__-/----/__-
// //__\          \      /   '  /    /   /    /   )
// )___(     _(____/____(___ __/____(___/____(___/_
// ======================================================================

// ======================================================================
// Copyright: (C) 2009-2012 Gregor Cramer
// ======================================================================

// ======================================================================
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
// ======================================================================

// IMPORTANT NOTE: keep the entries normalized!
static char const* Phrases200[] =
{
	/* 200 */	0,
	/* 201 */	"<xml>"
					"<:de>Eine Ungenauigkeit.</:de>"
					"<:en>An inaccuracy.</:en>"
					"<:es>Una inexactitud.</:es>"
					"<:fr>Une imprecision.</:fr>"
//					"<:hy></:hy>"
					"<:it>Poco precisa.</:it>"
					"<:ru>Неточность.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 202 */	"<xml>"
					"<:de>Ein Fehler.</:de>"
					"<:en>An error.</:en>"
					"<:es>Une erreur.</:es>"
					"<:fr></:fr>"
//					"<:hy></:hy>"
					"<:it>Un errore.</:it>"
					"<:ru>Ошибка.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 203 */	"<xml>"
					"<:de>Ein Patzer.</:de>"
					"<:en>A blunder.</:en>"
					"<:es>Grave error</:es>"
					"<:fr>Une gaffe.</:fr>"
//					"<:hy></:hy>"
					"<:it>Una svista.</:it>"
					"<:ru>Грубая ошибка.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 204 */	"<xml>"
					"<:de>Der zweite Fehler in Folge.</:de>"
					"<:en>The second error in a row.</:en>"
					"<:es>Segundo error consecutivo.</:es>"
					"<:fr>Une 2eme erreur d'affile.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il secondo errore di fila.</:it>"
					"<:ru>Вторая ошибка подряд.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 205 */	"<xml>"
					"<:de>Nicht die beste Fortsetzung.</:de>"
					"<:en>Not the best continuation.</:en>"
					"<:es>No es la mejor jugada.</:es>"
					"<:fr>Ce n'est pas la meilleure suite.</:fr>"
//					"<:hy></:hy>"
					"<:it>Non è la continuazione migliore.</:it>"
					"<:ru>Не лучшее продолжение.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 206 */	"<xml>"
					"<:de>Weiß kann den gegnerischen Fehler nicht zu seinem Vorteil nutzen.</:de>"
					"<:en>White fails to take advantage of the opponent's error.</:en>"
					"<:es>Las negras no aprovecharon el error del rival.</:es>"
					"<:fr>Les blancs ratent l'occasion de tirer avantage de l'erreur adverse. Plus fort est.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Bianco manca di sfruttare l'errore dell'avversario.</:it>"
					"<:ru>Белые не воспользовались ошибкой соперника.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 207 */	"<xml>"
					"<:de>Schwarz kann den gegnerischen Fehler nicht zu seinem Vorteil nutzen.</:de>"
					"<:en>Black fails to take advantage of the opponent's error.</:en>"
					"<:es>Las negras no aprovecharon el error del rival.</:es>"
					"<:fr>Les noirs ratent l'occasion de tirer avantage de l'erreur adverse. Plus fort est.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Nero manca di sfruttare l'errore dell'avversario.</:it>"
					"<:ru>Черные не воспользовались ошибкой соперника.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 208 */	0,
	/* 209 */	0,
	/* 210 */	0,
	/* 211 */	"<xml>"
					"<:de>Stärker ist</:de>"
					"<:en>Stronger is</:en>"
					"<:es>Mas fuerte es</:es>"
					"<:fr>Plus fort est</:fr>"
//					"<:hy></:hy>"
					"<:it>Più forte è</:it>"
					"<:ru>Сильнее было</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 212 */	"<xml>"
					"<:de>Vielversprechender ist</:de>"
					"<:en>More promising is</:en>"
					"<:es>Mas prometedor es</:es>"
					"<:fr>Plus prometteur est</:fr>"
//					"<:hy></:hy>"
					"<:it>Più promettente è</:it>"
					"<:ru>Перспективнее</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 213 */	"<xml>"
					"<:de>Vorzuziehen ist</:de>"
					"<:en>Preferable is</:en>"
					"<:es>Preferible era</:es>"
					"<:fr>Preferable est</:fr>"
//					"<:hy></:hy>"
					"<:it>È preferibile</:it>"
					"<:ru>Предпочтительнее было</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 214 */	"<xml>"
					"<:de>Beachtung verdient</:de>"
					"<:en>Worth attention is</:en>"
					"<:es>Interesante era</:es>"
					"<:fr>Merite attention</:fr>"
//					"<:hy></:hy>"
					"<:it>Merita attenzione</:it>"
					"<:ru>Заслуживало внимания</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 215 */	"<xml>"
					"<:de>Eine interessante Alternative ist</:de>"
					"<:en>An interesting alternative is</:en>"
					"<:es>La alternativa interesante era</:es>"
					"<:fr>Une alternative interessante est</:fr>"
//					"<:hy></:hy>"
					"<:it>Un'alternativa interessante è</:it>"
					"<:ru>Интересной альтернативой было</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 216 */	"<xml>"
					"<:de>Besser ist</:de>"
					"<:en>Better is</:en>"
					"<:es>Mejor era</:es>"
					"<:fr>Meilleur est</:fr>"
//					"<:hy></:hy>"
					"<:it>Migliore</:it>"
					"<:ru>Лучше</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 217 */	"<xml>"
					"<:de>Noch eigensinniger ist</:de>"
					"<:en>More stubborn is</:en>"
					"<:es>Mas resistente era</:es>"
					"<:fr>Plus subtil est</:fr>"
//					"<:hy></:hy>"
					"<:it>Più coriacea è</:it>"
					"<:ru>Упорнее было</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 218 */	0,
	/* 219 */	0,
	/* 220 */	0,
	/* 221 */	"<xml>"
					"<:de>bewahrt eine Vorteil.</:de>"
					"<:en>retains an advantage.</:en>"
					"<:es>Mantenia ventaja.</:es>"
					"<:fr>conserve l'avantage.</:fr>"
//					"<:hy></:hy>"
					"<:it>mantiene il vantaggio.</:it>"
					"<:ru>сохраняло перевес.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 222 */	"<xml>"
					"<:de>bewahrt eine ungefähre Ausgeglichenheit.</:de>"
					"<:en>retains an approximate equality.</:en>"
					"<:es>Mantenia aproximado equilibrio.</:es>"
					"<:fr>conduit a une egalite approximative.</:fr>"
//					"<:hy></:hy>"
					"<:it>mantiene una sostanziale parità.</:it>"
					"<:ru>сохраняло примерное равновесие.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 223 */	"<xml>"
					"<:de>gibt eine Möglichkeit um die Partie zu retten.</:de>"
					"<:en>gives a chance to save the game.</:en>"
					"<:es>dà la possibilità di salvare il gioco.</:es>"
					"<:fr>donne une chance de sauver le jeu.</:fr>"
//					"<:hy></:hy>"
					"<:it>da speranze per salvare la partita.</:it>"
					"<:ru>оставляло шансы на спасение.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 224 */	0,
	/* 225 */	0,
	/* 226 */	0,
	/* 227 */	0,
	/* 228 */	0,
	/* 229 */	0,
	/* 230 */	0,
	/* 231 */	"<xml>"
					"<:de>Weiß steht etwas besser.</:de>"
					"<:en>White stands slightly better.</:en>"
					"<:es>Las blancas estan mejor.</:es>"
					"<:fr>Les blancs sont legerement mieux (petit avantage).</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Bianco sta leggermente meglio.</:it>"
					"<:ru>У белых немного лучше.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 232 */	"<xml>"
					"<:de>Schwarz steht etwas besser.</:de>"
					"<:en>Black stands slightly better.</:en>"
					"<:es>Las negras estan mejor.</:es>"
					"<:fr>Les noirs sont legerement mieux (petit avantage).</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Nero sta leggermente meglio.</:it>"
					"<:ru>У черных немного лучше.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 233 */	"<xml>"
					"<:de>Die weißen Chancen sind etwas besser.</:de>"
					"<:en>White's chances are slightly better.</:en>"
					"<:es>Chances de las blancas son un poco mejores.</:es>"
					"<:fr>Les chances des blancs sont legerement superieures.</:fr>"
//					"<:hy></:hy>"
					"<:it>Le possibilità del Bianco sono leggermente migliori.</:it>"
					"<:ru>Шансы белых немного выше.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 234 */	"<xml>"
					"<:de>Die schwarzen Chancen sind etwas besser.</:de>"
					"<:en>Black's chances are slightly better.</:en>"
					"<:es>Chances de las negras son un poco mejores.</:es>"
					"<:fr>Les chances des noirs sont legerement superieures.</:fr>"
//					"<:hy></:hy>"
					"<:it>Le possibilità del Nero sono leggermente migliori.</:it>"
					"<:ru>Шансы черных немного выше.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 235 */	"<xml>"
					"<:de>Die weiße Position ist etwas vielversprechender.</:de>"
					"<:en>White's position is slightly more promising.</:en>"
					"<:es>La posicion de las blancas es un poco mas interesante.</:es>"
					"<:fr>La position blanche est plus prometteuse.</:fr>"
//					"<:hy></:hy>"
					"<:it>La posizione del Bianco è un po' più promettente.</:it>"
					"<:ru>Позиция белых неcколько перспективнее.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 236 */	"<xml>"
					"<:de>Die schwarze Position ist etwas vielversprechender.</:de>"
					"<:en>Black's position is slightly more promising.</:en>"
					"<:es>La posicion de las negras es un poco mas interesante.</:es>"
					"<:fr>La position noire est plus prometteuse.</:fr>"
//					"<:hy></:hy>"
					"<:it>La posizione del Nero è un po' più promettente.</:it>"
					"<:ru>Позиция черных неcколько перспективнее.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 237 */	"<xml>"
					"<:de>Die Chancen sind gleich.</:de>"
					"<:en>Chances are equal.</:en>"
					"<:es>Los chances son igualados.</:es>"
					"<:fr>Les chances sont egales.</:fr>"
//					"<:hy></:hy>"
					"<:it>Uguali possibilità.</:it>"
					"<:ru>Шансы сторон равны </:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 238 */	"<xml>"
					"<:de>Die Position ist ungefähr ausgeglichen.</:de>"
					"<:en>The position is approximately equal.</:en>"
					"<:es>La posicion es equilibrada.</:es>"
					"<:fr>La position est approximativement egale.</:fr>"
//					"<:hy></:hy>"
					"<:it>La posizione è sostanzialmente pari.</:it>"
					"<:ru>Позиция примерно равна.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 239 */	"<xml>"
					"<:de>Die Chancen sind verteilt.</:de>"
					"<:en>Chances are mutual.</:en>"
					"<:es>Ambos tienen chances.</:es>"
					"<:fr>Avec des chances des deux cotes.</:fr>"
//					"<:hy></:hy>"
					"<:it>Con possibilità da entrambi i lati.</:it>"
					"<:ru>Шансы сторон взаимны.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 240 */	"<xml>"
					"<:de>Zweischneidiges Spiel.</:de>"
					"<:en>Double-edged play.</:en>"
					"<:es>Juego complejo.</:es>"
					"<:fr>Jeu a double tranchant.</:fr>"
//					"<:hy></:hy>"
					"<:it>Con gioco a doppio taglio.</:it>"
					"<:ru>Обоюдоострая игра.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 241 */	"<xml>"
					"<:de>Weiß ist am gewinnen.</:de>"
					"<:en>White is winning.</:en>"
					"<:es>Las blancas estan ganando.</:es>"
					"<:fr>Les blancs gagnent.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Bianco sta vincendo.</:it>"
					"<:ru>У белых выиграно.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 242 */	"<xml>"
					"<:de>Schwarz ist am gewinnen.</:de>"
					"<:en>Black is winning.</:en>"
					"<:es>Las negras estan ganando.</:es>"
					"<:fr>Les noirs gagnent.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Nero sta vincendo.</:it>"
					"<:ru>У черных выиграно.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 243 */	"<xml>"
					"<:de>Weiß hat einen entscheidenden Vorteil.</:de>"
					"<:en>White has a decisive advantage.</:en>"
					"<:es>Las blancas tienen ventaja decisiva.</:es>"
					"<:fr>Les blancs ont un avantage decisif.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Bianco è in netto vantaggio.</:it>"
					"<:ru>У белых решающий перевес.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 244 */	"<xml>"
					"<:de>Schwarz hat einen entscheidenden Vorteil.</:de>"
					"<:en>Black has a decisive advantage.</:en>"
					"<:es>Las negras tienen ventaja decisiva.</:es>"
					"<:fr>Les noirs ont un avantage decisif.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Nero è in netto vantaggio.</:it>"
					"<:ru>У черных решающий перевес.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 245 */	"<xml>"
					"<:de>Weiß hat einige Initiative.</:de>"
					"<:en>White has an initiative.</:en>"
					"<:es>Las blancas tienen iniciativa.</:es>"
					"<:fr>Les blancs ont l'initiative.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Bianco ha l'iniziativa.</:it>"
					"<:ru>У белых инициатива.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 246 */	"<xml>"
					"<:de>Schwarz hat einige Initiative.</:de>"
					"<:en>Black has an initiative.</:en>"
					"<:es>Las negras tienen iniciativa.</:es>"
					"<:fr>Les noirs ont l'initiative.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Nero ha l'iniziativa.</:it>"
					"<:ru>У черных инициатива.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 247 */	"<xml>"
					"<:de>Der weiße König ist in Gefahr.</:de>"
					"<:en>White's king is in danger.</:en>"
					"<:es>El rey blanco esta en peligro.</:es>"
					"<:fr>Le roi blanc est en danger.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il re Bianco è in pericolo.</:it>"
					"<:ru>Белый король в опасности.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 248 */	"<xml>"
					"<:de>Der schwarze König ist in Gefahr.</:de>"
					"<:en>Black's king is in danger.</:en>"
					"<:es>El rey negro esta en peligro.</:es>"
					"<:fr>Le roi noir est en danger.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il re Nero è in pericolo.</:it>"
					"<:ru>Черный король в опасности.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 249 */	"<xml>"
					"<:de>Weiß entwickelt einen gefährlichen Angriff.</:de>"
					"<:en>White develops a dangerous attack.</:en>"
					"<:es>Las blancas desarollan un ataque peligroso.</:es>"
					"<:fr>Les blancs developpent une attaque dangereuse.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Bianco sviluppa un attacco pericoloso.</:it>"
					"<:ru>Белые развивают опасную атаку.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 250 */	"<xml>"
					"<:de>Schwarz entwickelt einen gefährlichen Angriff.</:de>"
					"<:en>Black develops a dangerous attack.</:en>"
					"<:es>Las negras desarollan un ataque peligroso.</:es>"
					"<:fr>Les noirs developpent une attaque dangereuse.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Nero sviluppa un attacco pericoloso.</:it>"
					"<:ru>Черные развивают опасную атаку.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 251 */	"<xml>"
					"<:de>Weiß hat das Läuferpaar.</:de>"
					"<:en>White has a pair of bishops.</:en>"
					"<:es>Las blancas tienen ventaja de pareja de alfiles.</:es>"
					"<:fr>Les blancs ont la paire de fous.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Bianco ha la coppia degli alfieri.</:it>"
					"<:ru>У белых преимущество 2-х слонов.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 252 */	"<xml>"
					"<:de>Schwarz hat das Läuferpaar.</:de>"
					"<:en>Black has a pair of bishops.</:en>"
					"<:es>Las negras tienen ventaja de pareja de alfiles.</:es>"
					"<:fr>Les noirs ont la paire de fous.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Nero ha la coppia degli alfieri.</:it>"
					"<:ru>У черных преимущество 2-х слонов.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 253 */	"<xml>"
					"<:de>Es ist eine ruhige Position entstanden mit einem kleinen weißen Vorteil.</:de>"
					"<:en>There arises a quiet position with a slight white advantage</:en>"
					"<:es>Tenemos la posicion tranquila con ligera ventaja de las blancas.</:es>"
					"<:fr>Une position tranquille survient avec un leger avantage blanc.</:fr>"
//					"<:hy></:hy>"
					"<:it>Si e creata una posizione tranquilla con un piccolo vantaggio per il Bianco.</:it>"
					"<:ru>Возникла спокойная позиция с небольшим перевесом белых.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 254 */	"<xml>"
					"<:de>Es ist eine ruhige Position entstanden mit einem kleinen schwarzen Vorteil.</:de>"
					"<:en>There arises a quiet position with a slight black advantage</:en>"
					"<:es>Tenemos la posicion tranquila con ligera ventaja de las negras.</:es>"
					"<:fr>Une position tranquille survient avec un leger avantage noir.</:fr>"
//					"<:hy></:hy>"
					"<:it>Si e creata una posizione tranquilla con un piccolo vantaggio per il Nero.</:it>"
					"<:ru>Возникла спокойная позиция с небольшим перевесом черных.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 255 */	"<xml>"
					"<:de>Der weiße König ist der Rochade beraubt.</:de>"
					"<:en>White king is deprived of castling.</:en>"
					"<:es>El rey blanco ha perdido el enroque.</:es>"
					"<:fr>Le roi blanc est prive du roque.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Bianco perde il diritto di arroccare.</:it>"
					"<:ru>Белый король лишился рокировки.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 256 */	"<xml>"
					"<:de>Der schwarze König ist der Rochade beraubt.</:de>"
					"<:en>Black king is deprived of castling.</:en>"
					"<:es>El rey negro ha perdido el enroque.</:es>"
					"<:fr>Le roi noir est prive du roque.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Nero perde il diritto di arroccare.</:it>"
					"<:ru>Черный король лишился рокировки.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 257 */	"<xml>"
					"<:de>Im bevorstehenden Endspiel sind die weißen Chancen etwas besser.</:de>"
					"<:en>In the ensuing endgame white's chances are slightly better.</:en>"
					"<:es>En el final chances de las blancas son un poco superiores.</:es>"
					"<:fr>Dans la finale qui s'en suit, les chances des blancs sont legerement superieures.</:fr>"
//					"<:hy></:hy>"
					"<:it>Nel finale a seguire il Bianco ha maggiori possibilità.</:it>"
					"<:ru>В возникшем эндшпиле шансы белых несколько выше.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 258 */	"<xml>"
					"<:de>Im bevorstehenden Endspiel sind die schwarzen Chancen etwas besser.</:de>"
					"<:en>In the ensuing endgame black's chances are slightly better.</:en>"
					"<:es>En el final chances de las negras son un poco superiores.</:es>"
					"<:fr>Dans la finale qui s'en suit, les chances des noirs sont legerement superieures.</:fr>"
//					"<:hy></:hy>"
					"<:it>Nel finale a seguire il Nero ha maggiori possibilità.</:it>"
					"<:ru>В возникшем эндшпиле шансы черных несколько выше.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 259 */	"<xml>"
					"<:de>Der Freibauer sichert Weiß einen Vorteil.</:de>"
					"<:en>A passed pawn secures an advantage for White.</:en>"
					"<:es>El peon pasado garantiza la ventaja a las blancas.</:es>"
					"<:fr>Le pion passe donne un avantage aux blancs.</:fr>"
//					"<:hy></:hy>"
					"<:it>Un pedone passato assicura il vantaggio Bianco.</:it>"
					"<:ru>Проходная пешка обеспечивает перевес белым.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 260 */	"<xml>"
					"<:de>Der Freibauer sichert Schwarz einen Vorteil.</:de>"
					"<:en>A passed pawn secures an advantage for Black.</:en>"
					"<:es>El peon pasado garantiza la ventaja a las negras.</:es>"
					"<:fr>Le pion passe donne un avantage aux noirs.</:fr>"
//					"<:hy></:hy>"
					"<:it>Un pedone passato assicura il vantaggio Nero.</:it>"
					"<:ru>Проходная пешка обеспечивает перевес черным.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 261 */	"<xml>"
					"<:de>Beiderseitiger Schlagabtausch.</:de>"
					"<:en>Both sides exchange blows.</:en>"
					"<:es>Los oponentes estan intercambiando golpes.</:es>"
					"<:fr>Les deux camps font des echanges.</:fr>"
//					"<:hy></:hy>"
					"<:it>Scambio di colpi da entrambi i lati.</:it>"
					"<:ru>Стороны обмениваются ударами.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 262 */	0,
	/* 263 */	"<xml>"
					"<:de>Eine unangenehme Fesselung, die Weiß einen Vorteil garantiert.</:de>"
					"<:en>An unpleasant pin granting a slight advantage to White.</:en>"
					"<:es>Clavada fastidiosa que da cierta ventaja a las blancas.</:es>"
					"<:fr>Un clouage deplaisant donnant un leger avantage aux blancs.</:fr>"
//					"<:hy></:hy>"
					"<:it>Un'inchiodatura fastidiosa garantisce un leggero vantaggio al Bianco.</:it>"
					"<:ru>Неприятная связка, дающая небольшой перевес белым.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 264 */	"<xml>"
					"<:de>Eine unangenehme Fesselung, die Schwarz einen Vorteil garantiert.</:de>"
					"<:en>An unpleasant pin granting a slight advantage to Black.</:en>"
					"<:es>Clavada fastidiosa que da cierta ventaja a las negras.</:es>"
					"<:fr>Un clouage deplaisant donnant un leger avantage aux noirs.</:fr>"
//					"<:hy></:hy>"
					"<:it>Un'inchiodatura fastidiosa garantisce un leggero vantaggio al Nero.</:it>"
					"<:ru>Неприятная связка, дающая небольшой перевес черным.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 265 */	"<xml>"
					"<:de>Weiß hat eine gute Kompensation für das geopferte Material.</:de>"
					"<:en>White has good compensation for sacrificed material.</:en>"
					"<:es>Las blancas tienen buena compensacion por el material.</:es>"
					"<:fr>Les blancs ont de bonnes compensations pour l'avantage materiel.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Bianco ha buon compenso per il materiale sacrificato.</:it>"
					"<:ru>У белых хорошая компенсация за материальный перевес.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 266 */	"<xml>"
					"<:de>Schwarz hat eine gute Kompensation für das geopferte Material.</:de>"
					"<:en>Black has good compensation for sacrificed material.</:en>"
					"<:es>Las negras tienen buena compensacion por el material.</:es>"
					"<:fr>Les noirs ont de bonnes compensations pour l'avantage materiel.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Nero ha buon compenso per il materiale sacrificato.</:it>"
					"<:ru>У черных хорошая компенсация за материальный перевес.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 267 */	"<xml>"
					"<:de>Weiß hat keine Kompensation für das Materialdefizit.</:de>"
					"<:en>White has no compensation for lacking material.</:en>"
					"<:es>Las blancas no tienen compensacion por el material.</:es>"
					"<:fr>Les blancs n'ont pas de compensation a leur perte de materiel.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Bianco non ha alcun compenso per il materiale in meno.</:it>"
					"<:ru>У белых нет компенсации за отсутствующий материал.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 268 */	"<xml>"
					"<:de>Schwarz hat keine Kompensation für das Materialdefizit.</:de>"
					"<:en>Black has no compensation for lacking material.</:en>"
					"<:es>Las negras no tienen compensacion por el material.</:es>"
					"<:fr>Les noirs n'ont pas de compensation a leur perte de materiel.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Nero non ha alcun compenso per il materiale in meno.</:it>"
					"<:ru>У черных нет компенсации за отсутствующий материал.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 269 */	"<xml>"
					"<:de>Weiß hat einen Materialvorteil.</:de>"
					"<:en>White has a material advantage.</:en>"
					"<:es>Las blancas tienen ventaja material.</:es>"
					"<:fr>Les blancs ont l'avantage materiel.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Bianco ha vantaggio materiale.</:it>"
					"<:ru>У белых материальный перевес</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 270 */	"<xml>"
					"<:de>Schwarz hat einen Materialvorteil.</:de>"
					"<:en>Black has a material advantage.</:en>"
					"<:es>Las negras tienen ventaja material.</:es>"
					"<:fr>Les noirs ont l'avantage materiel.</:fr>"
//					"<:hy></:hy>"
					"<:it>Il Nero ha vantaggio materiale.</:it>"
					"<:ru>У черных материальный перевес.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 271 */	"<xml>"
					"<:de>Das Schliessen der Position favorisiert Weiß.</:de>"
					"<:en>The ensuing closed position is favorable for White.</:en>"
					"<:es>La posicion cerrada que tenemos es ventajosa para las blancas.</:es>"
					"<:fr>La position fermee qui survient est favorable aux blancs.</:fr>"
//					"<:hy></:hy>"
					"<:it>La posizione chiusa a seguire favorisce il Bianco.</:it>"
					"<:ru>Возникшая закрытая позиция в пользу белых.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 272 */	"<xml>"
					"<:de>Das Schliessen der Position favorisiert Schwarz.</:de>"
					"<:en>The ensuing closed position is favorable for Black.</:en>"
					"<:es>La posicion cerrada que tenemos es ventajosa para las negras.</:es>"
					"<:fr>La position fermee qui survient est favorable aux noirs.</:fr>"
//					"<:hy></:hy>"
					"<:it>La posizione chiusa a seguire favorisce il Nero.</:it>"
					"<:ru>Возникшая закрытая позиция в пользу черных.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 273 */	0,
	/* 274 */	0,
	/* 275 */	0,
	/* 276 */	0,
	/* 277 */	0,
	/* 278 */	0,
	/* 279 */	0,
	/* 280 */	0,
	/* 281 */	0,
	/* 282 */	0,
	/* 283 */	0,
	/* 284 */	0,
	/* 285 */	0,
	/* 286 */	0,
	/* 287 */	0,
	/* 288 */	0,
	/* 289 */	0,
	/* 290 */	0,
	/* 291 */	"<xml>"
					"<:de>Mit der Drohung</:de>"
					"<:en>With a threat of</:en>"
					"<:es>Сon amenaza</:es>"
					"<:fr>Avec la menace</:fr>"
//					"<:hy></:hy>"
					"<:it>Minacciando</:it>"
					"<:ru>C угрозой</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 292 */	"<xml>"
					"<:de>Mit der Idee</:de>"
					"<:en>With the idea of</:en>"
					"<:es>Сon idea</:es>"
					"<:fr>Avec l'idee</:fr>"
//					"<:hy></:hy>"
					"<:it>Con l'idea</:it>"
					"<:ru>C идеей</:ru>"
//					"<:sv></:sv>"
					"</xml>",
};


// IMPORTANT NOTE: keep the entries normalized!
static char const* Phrases500[] =
{
	/* 500 */	0,
	/* 501 */	"<xml>"
					"<:de>Ein seltener Zug.</:de>"
					"<:en>A rare move.</:en>"
					"<:es>Una jugada rara.</:es>"
					"<:fr>Un coup rare.</:fr>"
//					"<:hy></:hy>"
					"<:it>Una mossa rara.</:it>"
					"<:ru>Редкий ход.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 502 */	"<xml>"
					"<:de>Die Hauptfortsetzung ist</:de>"
					"<:en>The main continuation is</:en>"
					"<:es>La continuacion principal es</:es>"
					"<:fr>La suite principale est</:fr>"
//					"<:hy></:hy>"
					"<:it>La continuazione principale è</:it>"
					"<:ru>Основное продолжение</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 503 */	"<xml>"
					"<:de>Neuerung!</:de>"
					"<:en>Novelty!</:en>"
					"<:es>¡Novedad!</:es>"
					"<:fr>Nouveaute!</:fr>"
//					"<:hy></:hy>"
					"<:it>Novità!</:it>"
					"<:ru>Новинка!</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 504 */	"<xml>"
					"<:de>Bisher wurde gespielt:</:de>"
					"<:en>Previously occured</:en>"
					"<:es>Se encontraba antes:</:es>"
					"<:fr>Deja vu</:fr>"
//					"<:hy></:hy>"
					"<:it>Avvenuto in precedenza.</:it>"
					"<:ru>Ранее встречалось</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 505 */	"<xml>"
					"<:de>Ein veralteter Zug.</:de>"
					"<:en>An old move.</:en>"
					"<:es>Jugada vieja.</:es>"
					"<:fr>Un coup ancien.</:fr>"
//					"<:hy></:hy>"
					"<:it>Una vecchia mossa.</:it>"
					"<:ru>Старый ход.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 506 */	"<xml>"
					"<:de>Neuerdings ist folgende Fortsetzung populärer:</:de>"
					"<:en>Recently more popular is the continuation:</:en>"
					"<:es>Ultimamente la continuacion mas popular es:</:es>"
					"<:fr>Recemment plus populaire est la suite:</:fr>"
//					"<:hy></:hy>"
					"<:it>Recentemente è più popolare la continuazione:</:it>"
					"<:ru>В последнее время популярнее продолжение:</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 507 */	"<xml>"
					"<:de>Dieser Zug wurde bisher nicht auf hohem Niveau angewandt.</:de>"
					"<:en>This move has not occurred at the high level before.</:en>"
					"<:es>Esta jugada nunca ha utilizada en los juegos de un alto nivel.</:es>"
					"<:fr>A ce jour, ce coup n’est jamais apparu au top niveau.</:fr>"
//					"<:hy></:hy>"
					"<:it>Questa mossa non si è ancora vista a livello magistrale.</:it>"
					"<:ru>Ход, не применявшийся на высоком уровне.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 508 */	"<xml>"
					"<:de>Führende Schachspieler bevorzugen</:de>"
					"<:en>Leading chessplayers prefer</:en>"
					"<:es>Los jugadores dirigentes prefieren</:es>"
					"<:fr>Les joueurs de haut niveau preferent</:fr>"
//					"<:hy></:hy>"
					"<:it>I più forti giocatori preferiscono</:it>"
					"<:ru>Ведущие шахматисты предпочитали</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 509 */	"<xml>"
					"<:de>Die solidere Alternative ist</:de>"
					"<:en>The more reliable continuation is</:en>"
					"<:es>La continuacion mas segura</:es>"
					"<:fr>Est une suite plus efficace</:fr>"
//					"<:hy></:hy>"
					"<:it>Una solida alternativa è</:it>"
					"<:ru>Более надежное продолжение</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 510 */	"<xml>"
					"<:de>Beachtung verdient</:de>"
					"<:en>Worth attention is</:en>"
					"<:es>Merece la atencion</:es>"
					"<:fr>Merite attention</:fr>"
//					"<:hy></:hy>"
					"<:it>Merita attenzione</:it>"
					"<:ru>Заслуживает внимания</:ru>"
//					"<:sv></:sv>"
					"</xml>",
	/* 511 */	"<xml>"
					"<:de>Dieser Zug wird immer populärer.</:de>"
					"<:en>This move becomes more and more unpopular.</:en>"
					"<:es>Esta jugada se pone a estar mas y mas popular.</:es>"
					"<:fr>Ce coup est de moins en moins apprecie.</:fr>"
//					"<:hy></:hy>"
					"<:it>Questa mossa sta diventando sempre piu impopolare.</:it>"
					"<:ru>Ход становится непопулярным.</:ru>"
//					"<:sv></:sv>"
					"</xml>",
};

// vi:set ts=3 sw=3:
