#define CT_RRP                             1
#define CT_UNKNOWN_SYM                     2
#define CT_INVALID_AT_SYM                  3
#define CT_SPACE                           4
#define CT_CHARSET_SYM                     5
#define CT_STRING                          6
#define CT_SEMICOLON                       7
#define CT_IMPORT_SYM                      8
#define CT_LP                              9
#define CT_RP                             10
#define CT_MEDIA_SYM                      11
#define CT_IDENT                          12
#define CT_COMMA                          13
#define CT_COLON                          14
#define CT_PAGE_SYM                       15
#define CT_FONT_SYM                       16
#define CT_IMPORTANT_SYM                  17
#define CT_PLUS                           18
#define CT_GT                             19
#define CT_STAR                           20
#define CT_HASH                           21
#define CT_DOT                            22
#define CT_LSP                            23
#define CT_RSP                            24
#define CT_EQUALS                         25
#define CT_TILDE                          26
#define CT_PIPE                           27
#define CT_SLASH                          28
#define CT_FUNCTION                       29
